config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks'}
  root 'static_public#landing_page'
  # get 'static_public/landing_page'
  get 'privacy', to: 'static_public#privacy'
  get 'terms', to: 'static_public#terms'
  resources :users, only: %i[index show]
  resources :questions do
    resources :answers
  end
  resources :topics do
    resources :topic_messages
  end
  resources :products do
    get :export, on: :collection
    post :import, on: :collection
  end
end

app/models/question.rb
class Question < ApplicationRecord
  has_many :answers, dependent: :destroy

  validates :title, presence: true, length: {minimum: 3}
  validates :body, presence: true, length: {minimum: 3}

  def formatted_created_at
    created_at.strftime('%Y-%m-%d %H:%M:%S')
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question!, only: %i[show destroy edit update]

  def index
    @questions = Question.all
  end

  def show
    @answer = @question.answers.build
    @answers = @question.answers.order created_at: :desc
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.new question_params
    if @question.save
      redirect_to questions_path
    else
      render :new
    end
  end

  def update
    if @question.update question_params
      redirect_to questions_path
    else
      render :edit
    end
  end

  def edit; end

  def destroy
    @question.destroy
    redirect_to questions_path

  end

  private

  def question_params
    params.require(:question).permit(:title, :body)
  end

  def set_question!
    @question = Question.find params[:id]
  end
end

app/views/questions/_form.html.erb
<%= form_with model: @question do |f| %>
  <div class="mb-3">
    <%= f.label :title %>
    <%= f.text_field :title, required: true, minlength: 3, class: 'form-control'  %>
  </div>
  <div class="mb-3">
    <%= f.label :body %>
    <%= f.text_area :body, required: true, minlength: 3, class: 'form-control'  %>
  </div>
  <div class="mb-3">
    <%= f.submit class: 'btn btn-outline-secondary' %>
  </div>
<% end %>

app/views/questions/edit.html.erb
<h2>Edit question</h2>
<%= render 'form' %>

app/views/questions/index.html.erb
<h2>All questions</h2>
<%= link_to 'new', new_question_path%>

<% @questions.each do |q| %>
  <h3><%= q.title %></h3>
  <time datetime="<%= q.formatted_created_at %>">
    <%= q.formatted_created_at %>
  </time>
  <p>
    <%= q.body %>
    <br>
    <%= link_to 'show', question_path(q)%>
    <%= link_to 'edit', edit_question_path(q)%>
    <%= link_to 'delete', question_path(q), method: :delete, data: {confirm: 'are you sure?'}%>
  </p>
  <br>
<% end %>

app/views/questions/new.html.erb
<h2>New question</h2>

<%= render 'form' %>

app/views/questions/show.html.erb
<h2><%= @question.title %></h2>
<p>
  <%= @question.body %>
  <br>
  <time datetime="<%= @question.formatted_created_at %>">
    <%= @question.formatted_created_at %>
  </time>
  <br>
  <%= link_to 'edit', edit_question_path(@question)%>
  <%= link_to 'delete', question_path(@question), method: :delete, data: {confirm: 'are you sure?'}%>
</p>

<%= form_with model: [@question, @answer] do |f|%>
    <div>
      <%= f.label :body %>
    </div>
    <div class="mb-3">
      <%=  f.text_area :body, class: 'form-control'%>
    </div>
  <%= f.submit class: 'btn btn-outline-secondary btn-sm' %>
<% end %>

<h2>Answers</h2>
<% @answers.each do |a| %>
  <%= a.body %>
  <%= link_to 'delete', question_answer_path(@question, a), method: :delete, data: {confirm: '?'} %>
  <br>
<% end %>