config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks'}
  root 'static_public#landing_page'
  # get 'static_public/landing_page'
  get 'privacy', to: 'static_public#privacy'
  get 'terms', to: 'static_public#terms'
  resources :users, only: %i[index show]
  resources :questions do
    resources :answers
  end
  resources :topics do
    resources :topic_messages
  end
  resources :products do
    get :export, on: :collection
    post :import, on: :collection
  end
end

app/models/topic.rb
class Topic < ApplicationRecord
  has_many :topic_messages
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_topic, only: %i[show edit update destroy]

  def index
    @topics = Topic.all
  end

  def show
    @topic_message = @topic.topic_messages.build
    @topic_messages = @topic.topic_messages.order created_at: :desc
  end

  def new
    @topic = Topic.new
  end

  def edit; end

  def create
    @topic = Topic.new(topic_params)

    respond_to do |format|
      if @topic.save
        format.html { redirect_to topics_url, notice: 'Обсуждение сохранено.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @topic.update(topic_params)
        format.html { redirect_to topics_url, notice: 'Обсуждение сохранено.' }
      else
        format.html { render :edit }
      end
    end
  end


  def destroy
    @topic.destroy
    respond_to do |format|
      format.html { redirect_to topics_url, notice: 'Topic was successfully destroyed.' }
    end
  end


  private

  def set_topic
    @topic = Topic.find(params[:id])
  end

  def topic_params
    params.require(:topic).permit(:name)
  end


end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_form.html.erb
<%= form_for @topic do |f| %>
  <% if @topic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@topic.errors.count, "error") %> prohibited this topic from being saved:</h2>

      <ul>
        <% @topic.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
    <div class="form-group mb-3">
      <%= f.label 'Имя' %><br>
      <%= f.text_field :name, class: 'form-control', required: true %>
    </div>
    <div class="actions mb-3">
      <%= f.submit "Сохранить", class: "btn btn-outline-success btn-sm" %>
    </div>
<% end %>

app/views/topics/_topic_message_form.html.erb
<%= form_with model: [@topic, @topic_message] do |f|%>
  <div class="mb-3">
    <%= f.text_area :body, rows: 2, class: 'form-control', placeholder: 'Введите сообщение' %>
    <%#= f.text_field :user_id, class: 'form-control' %>
  </div>
  <%= f.submit "Отправить", class: "btn btn-outline-success btn-sm" %>
<% end %>

app/views/topics/edit.html.erb
<div class="card">
  <div class="card-body">
    <div class="card-title mb-3">
      <h3>
        <%= link_to 'Назад', topics_path, class: 'btn btn-outline-secondary btn-sm' %>
        <div class="ps-2">
          Редактировать обсуждение
        </div>
      </h3>
    </div>
    <%= render 'form' %>
  </div>
</div>

app/views/topics/index.html.erb
<div class="card">
  <div class="card-body">
    <div class="card-title">
      <%= link_to 'Добавить обсуждение', new_topic_path, class: 'btn btn-outline-success btn-sm' %>
    </div>
    <br/>
    <table class="table table-striped">
      <tbody>
      <% @topics.each do |topic| %>
        <tr>
          <td>
            <%= link_to topic.name, topic %>
          </td>
          <td align="right">
            <%=link_to edit_topic_path(topic.id) do %>
              <i class="far fa-edit"></i>
            <% end %>
            <%= link_to topic_path(topic.id), method: :delete, data: { confirm: 'Вы уверены?' } do %>
              <i class="far fa-trash-alt"></i>
            <% end %>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/topics/new.html.erb
<div class="card">
  <div class="card-body">
    <div class="card-title mb-3">
      <h3>
        <%= link_to 'Назад', topics_path, class: 'btn btn-outline-secondary btn-sm' %>
        <div class="ps-2">
          Новое обсуждение
        </div>
      </h3>
    </div>
    <%= render 'form' %>
  </div>
</div>

app/views/topics/show.html.erb
<div class="card">
  <div class="card-body">
    <div class="card-title mb-3">
      <h3>
        <%= link_to 'Назад', topics_path, class: 'btn btn-outline-secondary btn-sm' %>
        <div class="ps-2"><%= @topic.name %></div>
      </h3>
    </div>

    <%= render 'topic_message_form' %>
    <br>
    <h3>Все сообщения:</h3>
    <hr>
    <% @topic_messages.each do |topic_message| %>
      <div class="row">
        <div class="col">
          <b><%= User.find_by_id(topic_message.user_id).try(:name)%></b> &nbsp;
          <%=l(topic_message.created_at, format: :long)%> &nbsp;
          <%=link_to edit_topic_topic_message_path(@topic, topic_message) do %>
            <i class="far fa-edit"></i>
          <% end %>
          <%= link_to topic_topic_message_path(@topic, topic_message), method: :delete, data: { confirm: 'Вы уверены?' } do %>
            <i class="far fa-trash-alt"></i>
          <% end %>
        </div>
      </div>
      <div class="row">
        <div class="col">
          <%= topic_message.body %>
        </div>
      </div>
      <br>
    <% end %>
  </div>
</div>