config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks'}
  root 'static_public#landing_page'
  # get 'static_public/landing_page'
  get 'privacy', to: 'static_public#privacy'
  get 'terms', to: 'static_public#terms'
  resources :users, only: %i[index show]
  resources :questions do
    resources :answers
  end
  resources :topics do
    resources :topic_messages
  end
  resources :products do
    get :export, on: :collection
    post :import, on: :collection
  end
end

app/models/product.rb
class Product < ApplicationRecord
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy ]

  # GET /products or /products.json
  def index
    @q = Product.order(:name).ransack(params[:q])
    @pagy, @products = pagy(@q.result(distinct: true))

    respond_to do |format|
      format.html
      format.json {
        render json: { entries: render_to_string(partial: 'products', formats: [:html]),
                       pagination: view_context.pagy_bootstrap_nav(@pagy) }
      }
    end
  end

  # GET /products/1 or /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def export
    @products = Product.all
    render xlsx: 'create', template: 'products/export'
  end

  def import
    file = params[:file].tempfile
    spreadsheet = Roo::Excelx.new(file).to_a
    spreadsheet.each do |item_array|
      #id = item_array[0]
      name = item_array[0]
      price = item_array[2]
      in_stock = item_array[1]

      product = Product.find_or_create_by(name: name)
      product.update(name: name, price: price, in_stock: in_stock)
    end
    redirect_to products_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
  def set_product
    @product = Product.find(params[:id])
  end

    # Only allow a list of trusted parameters through.
  def product_params
    params.require(:product).permit(:name, :price, :in_stock)
  end
end

app/views/products/_form.html.erb
<%= form_with(model: product) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="mb-3">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="mb-3">
    <%= form.label :in_stock %>
    <%= form.number_field :in_stock %>
  </div>

  <div class="mb-3">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/_products.html.erb
<% @products.each do |product| %>
  <div class="d-flex justify-content-between ">
    <%= product.name %>
    <div class="d-flex justify-content-end">
      <%= product.price %>&nbsp;
      <%= product.in_stock %>&nbsp;
      <%= link_to 'Show', product %>&nbsp;
      <%= link_to 'Edit', edit_product_path(product) %>&nbsp;
      <%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %>
    </div>
  </div>
  <hr>
<% end %>

app/views/products/edit.html.erb
<h2>Editing Product</h2>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<h2>Products</h2>

<%= link_to 'New Product', new_product_path %> |
<%= link_to 'Export Products', export_products_path %>
<hr>
<%= form_tag import_products_path, multipart: true do %>
  <%= file_field_tag :file %>
  <%= submit_tag "Import" %>
<% end %>
<hr>
<div class="d-flex">
  <div>
    <%= search_form_for @q do |f| %>
      <%= f.label :name_cont %>
      <%= f.search_field :name_cont %>
      <%= f.submit %>
    <% end %>
  </div>
  <div class="ps-3 align-items-center">
    <% if params[:q].present? %>
      <%= link_to products_path do %>
        <i class="fa fa-sync"></i>
      <% end %>
    <% end %>
  </div>
</div>
<hr>

  <div data-controller="infinite-scroll">
     <div data-infinite-scroll-target="entries">
       <%= render 'products' %>
     </div>
     <div data-infinite-scroll-target="pagination" class="visually-hidden">
      <%== pagy_bootstrap_nav @pagy %>
     </div>
<!--    <div class="d-flex justify-content-center">-->
<!--      <div class="spinner-border" role="status">-->
<!--        <span class="visually-hidden">Загрузка...</span>-->
<!--      </div>-->
<!--    </div>-->
  </div>

app/views/products/new.html.erb
<h2>New Product</h2>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>In stock:</strong>
  <%= @product.in_stock %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>