config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks'}
  root 'static_public#landing_page'
  # get 'static_public/landing_page'
  get 'privacy', to: 'static_public#privacy'
  get 'terms', to: 'static_public#terms'
  resources :users, only: %i[index show]
  resources :questions do
    resources :answers
  end
  resources :topics do
    resources :topic_messages
  end
  resources :products do
    get :export, on: :collection
    post :import, on: :collection
  end
end

app/views/layouts/_footer.html.erb
<div class="bg-light text-center">
  <br>
  <div class="container">
    <div class="row align-items-start">
      <div class="col-sm-4">
        some text
      </div>
      <div class="col-sm-4">
        <%= link_to privacy_path, class: " #{'active fw-bold' if current_page?(privacy_path)}" do %>
          <div class="fa fa-file-contract"></div>
          Privacy
        <% end %>
      </div>
      <div class="col-sm-4">
        <%= link_to terms_path, class: " #{'active fw-bold' if current_page?(terms_path)}" do %>
          <div class="fa fa-file-contract"></div>
          Terms
        <% end %>
      </div>
    </div>
  </div>
  <br>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light fixed-top pb-2" style="background-color: #ffffff;" >
  <div class="container-fluid">
    <div class="navbar-brand">
      
    </div>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <%= link_to root_path, class: "nav-link #{'active fw-bold' if current_page?(root_path)}" do %>
          <div class="fa fa-home"></div>
          Home
        <% end %>
        <%= link_to products_path, class: "nav-link #{'active fw-bold' if current_page?(products_path)}" do %>
          <div class="fa fa-folder"></div>
          Products
        <% end %>
        <%= link_to questions_path, class: "nav-link #{'active fw-bold' if current_page?(questions_path)}" do %>
          <div class="fa fa-question-circle"></div>
          Questions
        <% end %>
        <%= link_to topics_path, class: "nav-link #{'active fw-bold' if current_page?(topics_path)}" do %>
          <div class="fa fa-comments"></div>
          Topics
        <% end %>
        <% if current_user %>
          <%= link_to users_path, class: "nav-link #{'active fw-bold' if current_page?(users_path)}" do %>
            <div class="fa fa-users"></div>
            Users
          <% end %>
        <% end %>
      </ul>
      <ul class="navbar-nav ms-auto">
        <% if current_user %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <% if current_user.image? %>
                <%= image_tag current_user.image, size: "30x30", class: "rounded-circle"%>
              <% else %>
                <div class="fa fa-user"></div>
              <% end %>
              <%= current_user.username %>
            </a>
            <ul class="dropdown-menu dropdown-menu-lg-end" aria-labelledby="navbarDropdown">
              <%= link_to user_path(current_user), class: "dropdown-item #{'active fw-bold' if current_page?(user_path(current_user))}" do %>
                <div class="fa fa-user"></div>
                <b>My profile</b>
              <% end %>
              <%= link_to edit_user_registration_path, class: "dropdown-item #{'active fw-bold' if current_page?(edit_user_registration_path)}" do %>
                <div class="fa fa-cog"></div>
                <b>Account settings</b>
              <% end %>
              <%= link_to destroy_user_session_path, method: :delete, class: "dropdown-item" do %>
                <div class="fa fa-sign-out-alt"></div>
                <b>Sign out</b>
              <% end %>
            </ul>
          </li>
        <% else %>
          <%= link_to "Log in", new_user_session_path, class: "nav-link #{'active fw-bold' if current_page?(new_user_session_path)}" %>
          <%= link_to "Sign up", new_user_registration_path, class: "nav-link #{'active fw-bold' if current_page?(new_user_registration_path)}" %>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Remotronic Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag "favicon-32x32.png" %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;600;700&display=swap" rel="stylesheet">

  </head>

  <body >
    <%= render 'layouts/header' %>
    <div class="container">
      <div class="row pt-5">
        <div class="col-md-12 col-lg-12 pt-2">
          <%  if notice.present? %>
            <div class="alert alert-success alert-dismissible">
              <%=notice %>
              <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
          <%  elsif alert.present? %>
            <div class="alert alert-danger alert-dismissible">
              <%=alert %>
              <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
          <% end %>
          <div class="pt-2">
            <%= yield %>
          </div>
        </div>
      </div>
    </div>
    </body>
  <footer>
    <%= render 'layouts/footer' %>
  </footer>
</html>